// ─── src/components/KillSwitchModal.jsx ──────────────────────────────────────
// Kill Switch modal — Gemini script + confirm removes subscription from state.

import { useEffect, useState } from 'react'
import {
  X, Zap, Copy, Check, ExternalLink,
  AlertTriangle, Loader2, Sparkles, Bot,
} from 'lucide-react'
import { useGeminiRetention } from '../hooks/useGeminiRetention'
import { DEFAULT_RETENTION_SCRIPT, DEFAULT_SWAP } from '../data/subscriptions'

export default function KillSwitchModal({ subscription, profile, onClose, onConfirmKill }) {
  const { generate, script, loading, usingFallback } = useGeminiRetention(profile)
  const [copied, setCopied] = useState(false)

  const swap = subscription.swap || DEFAULT_SWAP

  useEffect(() => {
    const enriched = {
      ...subscription,
      swap,
      retentionScript:
        subscription.retentionScript || DEFAULT_RETENTION_SCRIPT(subscription, profile),
    }
    generate(enriched)
    document.body.style.overflow = 'hidden'
    return () => { document.body.style.overflow = '' }
  }, [subscription.id, profile, generate])

  useEffect(() => {
    const handler = (e) => { if (e.key === 'Escape') onClose() }
    window.addEventListener('keydown', handler)
    return () => window.removeEventListener('keydown', handler)
  }, [onClose])

  async function handleCopy() {
    if (!script) return
    try {
      await navigator.clipboard.writeText(script)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch {
      /* clipboard unavailable */
    }
  }

  function handleConfirm() {
    onConfirmKill(subscription.id)
    window.open(subscription.url, '_blank', 'noopener,noreferrer')
  }

  return (
    <div
      className="fixed inset-0 z-50 flex items-end sm:items-center justify-center p-0 sm:p-4 modal-backdrop bg-black/70"
      role="dialog"
      aria-modal="true"
      aria-labelledby="modal-title"
      onClick={(e) => { if (e.target === e.currentTarget) onClose() }}
    >
      <div
        className="glass-card rounded-t-3xl sm:rounded-2xl w-full sm:max-w-lg max-h-[90vh] flex flex-col overflow-hidden border border-zinc-800/90 shadow-2xl"
        style={{ animation: 'modal-in 0.35s cubic-bezier(0.16,1,0.3,1) forwards' }}
      >
        <div className="flex items-start justify-between p-5 border-b border-zinc-800/80">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 rounded-xl bg-rose-500/15 border border-rose-500/30 flex items-center justify-center">
              <Zap size={16} className="text-rose-400" />
            </div>
            <div>
              <h2 id="modal-title" className="font-display font-bold text-white text-base leading-tight">
                Kill Switch — {subscription.name}
              </h2>
              <p className="text-[10px] font-mono text-white/30 uppercase tracking-widest mt-0.5">
                Retention Optimizer
              </p>
            </div>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="w-8 h-8 rounded-lg bg-white/5 hover:bg-white/10 flex items-center justify-center transition-colors text-white/40 hover:text-white/80"
            aria-label="Close modal"
          >
            <X size={15} />
          </button>
        </div>

        <div className="flex-1 overflow-y-auto p-5 space-y-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              {usingFallback
                ? <Bot size={13} className="text-amber-400" />
                : <Sparkles size={13} className="text-violet-400" />
              }
              <span className="text-[10px] font-mono uppercase tracking-widest text-white/30">
                {loading
                  ? 'Generating with Gemini AI…'
                  : usingFallback
                    ? 'Pre-written retention script'
                    : 'Generated by Gemini AI'
                }
              </span>
            </div>

            {!loading && script && (
              <button
                type="button"
                onClick={handleCopy}
                className="flex items-center gap-1.5 text-[10px] font-mono text-white/40 hover:text-white/80 transition-colors px-2 py-1 rounded bg-white/5 hover:bg-white/10"
                aria-label="Copy script to clipboard"
              >
                {copied
                  ? <><Check size={11} className="text-emerald-400" /> Copied!</>
                  : <><Copy size={11} /> Copy script</>
                }
              </button>
            )}
          </div>

          <div className="relative min-h-[140px] rounded-xl bg-white/[0.03] border border-zinc-800/80 p-4">
            {loading ? (
              <div className="flex flex-col items-center justify-center gap-3 py-6">
                <Loader2 size={20} className="text-rose-400 animate-spin" />
                <p className="text-xs text-white/30 font-mono">
                  Crafting your negotiation script…
                </p>
                <div className="flex gap-1">
                  {[0, 1, 2].map((i) => (
                    <div
                      key={i}
                      className="w-1.5 h-1.5 rounded-full bg-rose-500/40 shimmer-bg"
                      style={{ animationDelay: `${i * 0.2}s` }}
                    />
                  ))}
                </div>
              </div>
            ) : (
              <p className="text-sm text-white/75 font-body leading-relaxed whitespace-pre-wrap">
                {script}
              </p>
            )}
          </div>

          <div className="flex items-start gap-2.5 rounded-xl bg-amber-500/5 border border-amber-500/15 p-3.5">
            <AlertTriangle size={13} className="text-amber-400 flex-shrink-0 mt-0.5" />
            <p className="text-xs text-white/50 font-body leading-snug">
              Paste this into the live chat or email the support team.
              Mentioning a specific free alternative (
              <span className="text-amber-400 font-mono text-[11px]">{swap.name}</span>
              ) significantly increases your chance of getting a discount.
            </p>
          </div>
        </div>

        <div className="p-5 border-t border-zinc-800/80 flex gap-3">
          <button
            type="button"
            onClick={onClose}
            className="flex-1 py-2.5 rounded-xl bg-white/5 hover:bg-white/10 text-white/60 hover:text-white text-sm font-display font-medium transition-all"
          >
            Keep Subscription
          </button>
          <button
            type="button"
            onClick={handleConfirm}
            className="flex-1 py-2.5 rounded-xl bg-rose-500 hover:bg-rose-400 text-white text-sm font-display font-bold transition-all kill-pulse flex items-center justify-center gap-2 shadow-lg shadow-rose-500/20"
          >
            <ExternalLink size={14} />
            Cancel Now
          </button>
        </div>
      </div>
    </div>
  )
}
