// ─── src/utils/icsGenerator.js ────────────────────────────────────────────────
// Generates and auto-downloads a standard .ics calendar file via Blob API.

function formatICSDate(date) {
  return date.toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z'
}

function generateUID(subscriptionId) {
  const rand = Math.random().toString(36).substring(2, 10)
  const ts = Date.now()
  return `subsidized-${subscriptionId}-${ts}-${rand}@subsidized.app`
}

export function downloadICS(subscription, daysFromNow) {
  const days = daysFromNow ?? subscription.trialDeadlineDays ?? 30

  const deadline = new Date()
  deadline.setDate(deadline.getDate() + days)
  deadline.setHours(9, 0, 0, 0)

  const end = new Date(deadline)
  end.setHours(10, 0, 0, 0)

  const alarmTrigger = '-P1D'
  const uid = generateUID(subscription.id)
  const now = formatICSDate(new Date())
  const dtStart = formatICSDate(deadline)
  const dtEnd = formatICSDate(end)
  const cancelUrl = subscription.url

  const icsContent = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//SUBsidized//Kill Your Subscriptions//EN',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
    'BEGIN:VEVENT',
    `UID:${uid}`,
    `DTSTAMP:${now}`,
    `DTSTART:${dtStart}`,
    `DTEND:${dtEnd}`,
    `SUMMARY:⚠️ SUBsidized: Cancel ${subscription.name} ${subscription.plan} Today!`,
    `DESCRIPTION:Your ${subscription.name} ${subscription.plan} trial deadline is TODAY.\\n\\nMonthly cost: RM${subscription.cost.toFixed(2)}\\nYearly cost: RM${(subscription.cost * 12).toFixed(2)}\\n\\nCancel now at: ${cancelUrl}\\n\\nGenerated by SUBsidized — Kill Your Subscriptions`,
    `URL:${cancelUrl}`,
    `LOCATION:${cancelUrl}`,
    'STATUS:CONFIRMED',
    'TRANSP:OPAQUE',
    'BEGIN:VALARM',
    'ACTION:DISPLAY',
    `DESCRIPTION:⚠️ Cancel ${subscription.name} NOW — RM${subscription.cost.toFixed(2)}/mo at stake!`,
    `TRIGGER:${alarmTrigger}`,
    'END:VALARM',
    'BEGIN:VALARM',
    'ACTION:DISPLAY',
    `DESCRIPTION:⚠️ FINAL REMINDER: Cancel ${subscription.name} today!`,
    'TRIGGER:PT0S',
    'END:VALARM',
    'END:VEVENT',
    'END:VCALENDAR',
  ].join('\r\n')

  const blob = new Blob([icsContent], { type: 'text/calendar;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')

  link.href = url
  link.download = `cancel-${subscription.id}-deadline.ics`
  document.body.appendChild(link)
  link.click()

  document.body.removeChild(link)
  setTimeout(() => URL.revokeObjectURL(url), 1000)
}
